from dataclasses import dataclass
from typing import Literal, Protocol

from dzen_commenter.contracts.enums import CommentStatus, ReplyStatus
from dzen_commenter.contracts.models import Comment, Publication, Reply

ReplyType = Literal["lead", "engage"]


@dataclass
class PromptContext:
    publication_title: str
    thread_text: str
    reply_type: ReplyType
    comment_text: str = ""


class CommentRepository(Protocol):
    def upsert_publication(self, pub: Publication) -> int: ...
    def upsert_comment(self, comment: Comment) -> int: ...
    def save_reply(self, reply: Reply) -> int: ...
    def set_comment_status(self, comment_id: int, status: CommentStatus) -> None: ...
    def set_reply_status(
        self, reply_id: int, status: ReplyStatus, error_reason: str | None = None
    ) -> None: ...
    def has_generated_reply(self, comment_id: int) -> bool: ...
    def has_published_reply(self, comment_id: int) -> bool: ...


class AIProvider(Protocol):
    def generate(self, prompt: str, *, temperature: float, max_tokens: int) -> str: ...


class PromptBuilder(Protocol):
    def build(self, context: PromptContext) -> str: ...


class SessionManager(Protocol):
    def start(self) -> None: ...
    def is_logged_in(self) -> bool: ...
    def login(self) -> bool: ...
    def save_state(self) -> None: ...
    def restore(self) -> bool: ...
    def reset_authentication(self) -> None: ...


class DzenPage(Protocol):
    def fetch_comments(self) -> list[Comment]: ...
    def publish_reply(
        self, comment: Comment, text: str, *, auto_publish: bool
    ) -> None: ...


class Notifier(Protocol):
    def notify(self, message: str) -> None: ...
    def notify_error(self, message: str, error: Exception | None = None) -> None: ...


class AuthAssistant(Protocol):
    def poll_auth_command(self) -> bool: ...
    def reset_ready_prompt(self) -> None: ...
    def ask_ready(self) -> bool: ...
    def notify_sms_restart(self) -> None: ...
    def notify_sms_pending(self) -> None: ...
    def relay_code_prompt(self, prompt_text: str) -> str: ...
